# Generated by Django 6.0.6 on 2026-07-02 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('CAO', 'Cachorro'), ('GATO', 'Gato')], max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível para adoção'), ('TRATAMENTO', 'Em tratamento'), ('ADOTADO', 'Adotado')], default='DISPONIVEL', max_length=20)),
                ('vacinado', models.BooleanField(default=False)),
                ('castrado', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('nivel_energia', models.IntegerField(blank=True, choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], null=True)),
                ('necessidade_espaco', models.IntegerField(blank=True, choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], null=True)),
                ('convive_criancas', models.IntegerField(blank=True, choices=[(1, 'Não'), (2, 'Depende'), (3, 'Sim')], null=True)),
                ('convive_animais', models.IntegerField(blank=True, choices=[(1, 'Não'), (2, 'Depende'), (3, 'Sim')], null=True)),
                ('experiencia_tutor', models.IntegerField(blank=True, choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Experiente')], null=True)),
                ('tempo_diario', models.IntegerField(blank=True, choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto')], null=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('perfil_ia', models.TextField(blank=True)),
                ('codigo_compatibilidade', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
