# Generated by Django 6.0.6 on 2026-07-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('residencia', models.CharField(blank=True, max_length=50, null=True)),
                ('quintal', models.CharField(blank=True, max_length=10, null=True)),
                ('criancas', models.CharField(blank=True, max_length=10, null=True)),
                ('experiencia', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo', models.CharField(blank=True, max_length=20, null=True)),
                ('outros_animais', models.CharField(blank=True, max_length=10, null=True)),
                ('perfil', models.CharField(blank=True, max_length=30, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('compatibilidade', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.animal')),
            ],
        ),
    ]
