# Generated by Django 6.0.6 on 2026-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_adotante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adotante',
            old_name='compatibilidade',
            new_name='compatibilidade_nota',
        ),
        migrations.RenameField(
            model_name='adotante',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='adotante',
            name='compatibilidade_relatorio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='perfil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='tempo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
